[tool.poetry]
name = "FLock-subnet"
version = "0.2.0"
description = "FLock Subnet"
authors = ["Flock Devs"]
readme = "README.md"
packages = [
    {include = "FLockDataset"},
    {include = "neurons"}
]

[tool.poetry.dependencies]
python = "^3.9"
bittensor = "^6.9.3"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
