name: Unit Test

on:
  push:
    branches: [ "main", "testnet" ]
  pull_request:
    branches: [ "main", "testnet" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync
          uv pip install -e .

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest
